function OA_AddResolutionMarker(ax, x_nm, label_text, line_color, y_text, plot_style)
    if isnan(x_nm) || ~isfinite(x_nm)
        return;
    end

    xline(ax, x_nm, '--', ...
        'Color', line_color, ...
        'LineWidth', plot_style.line_width_light, ...
        'HandleVisibility', 'off');

    xl = xlim(ax);
    yl = ylim(ax);
    xr = xl(2) - xl(1);
    yr = yl(2) - yl(1);

    if x_nm < xl(1) + 0.75 * xr
        x_text = x_nm + 0.014 * xr;
        h_align = 'left';
    else
        x_text = x_nm - 0.014 * xr;
        h_align = 'right';
    end

    % 自动限制文字位置，避免顶部显示不全
    y_text = min(y_text, yl(2) - 0.08 * yr);
    y_text = max(y_text, yl(1) + 0.25 * yr);

    text(ax, x_text, y_text, label_text, ...
        'Color', line_color, ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_legend, ...
        'FontWeight', 'bold', ...
        'Rotation', 90, ...
        'Interpreter', 'tex', ...
        'HorizontalAlignment', h_align, ...
        'VerticalAlignment', 'top', ...
        'BackgroundColor', 'w', ...
        'Margin', 2, ...
        'Clipping', 'on');
end
