function OA_FormatPlotAxes(ax, plot_style)
    set(ax, ...
        'Color', 'w', ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_axis, ...
        'LineWidth', plot_style.axis_line_width, ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'Box', 'on', ...
        'Layer', 'top');
    grid(ax, 'on');
    try
        ax.GridAlpha = plot_style.grid_alpha;
        ax.MinorGridAlpha = 0.7 * plot_style.grid_alpha;
    catch
    end
end
