function PSI_FormatNatureMetricAxes(ax, plot_style)
    set(ax, ...
        'Color', 'w', ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_axis, ...
        'LineWidth', 0.85, ...
        'XColor', [0.05 0.05 0.05], ...
        'YColor', [0.05 0.05 0.05], ...
        'Box', 'off', ...
        'TickDir', 'in', ...
        'TickLength', [0.012 0.012], ...
        'Layer', 'top');
    ax.XGrid = 'off';
    ax.YGrid = 'on';
    try
        ax.GridColor = [0.2 0.2 0.2];
        ax.GridAlpha = 0.10;
    catch
    end
end
