function PSI_FormatLegendNature(lgd, ps)
    set(lgd, 'FontName', ps.font_name, ...
        'FontSize', ps.font_size_legend, ...
        'Box', 'off', ...
        'Color', 'none', ...
        'TextColor', [0.10 0.10 0.10]);
    try
        lgd.ItemTokenSize = [8 6];
    catch
    end
end
