function PSI_FormatProfileAxesNature_Multi(ax, ps)
    set(ax, 'FontName', ps.font_name, ...
        'FontSize', ps.font_size_axis, ...
        'LineWidth', ps.axis_line_width, ...
        'TickDir', 'out', ...
        'TickLength', [0.010 0.010], ...
        'Box', 'off', ...
        'Layer', 'top', ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'XMinorTick', 'off', ...
        'YMinorTick', 'off');
    grid(ax, 'off');

    ax.XLabel.FontName = ps.font_name;
    ax.YLabel.FontName = ps.font_name;
    ax.Title.FontName  = ps.font_name;

    ax.XLabel.FontSize = ps.font_size_label;
    ax.YLabel.FontSize = ps.font_size_label;
    ax.Title.FontSize  = ps.font_size_title;
    ax.Title.FontWeight = 'normal';
end
