function PSI_FormatLegend_OA(lgd, plot_style)
    set(lgd, ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_legend, ...
        'Box', 'on', ...
        'Color', 'w', ...
        'TextColor', 'k', ...
        'EdgeColor', 'k');
end
