function PSI_FormatLegend(lgd, plot_style)
    set(lgd, ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_legend, ...
        'Box', 'off', ...
        'Color', 'none', ...
        'TextColor', [0.10 0.10 0.10]);
end
