function PSI_FormatNatureColorbar(cb, plot_style)
    try
        set(cb, ...
            'Color', [0.10 0.10 0.10], ...
            'FontName', plot_style.font_name, ...
            'FontSize', plot_style.font_size_axis, ...
            'LineWidth', 0.75, ...
            'TickDirection', 'in', ...
            'Box', 'off');
    catch
        set(cb, ...
            'Color', [0.10 0.10 0.10], ...
            'FontName', plot_style.font_name, ...
            'FontSize', plot_style.font_size_axis, ...
            'LineWidth', 0.75);
    end
end
