function PSI_formatCurveAxes(ax)
    % Compact publication-style formatting for line-plot panels.
    if nargin < 1 || isempty(ax), ax = gca; end
    set(ax, ...
        'FontName','Arial', ...
        'FontSize',7.0, ...
        'LineWidth',0.75, ...
        'TickDir','in', ...
        'TickLength',[0.016 0.016], ...
        'Box','off', ...
        'Layer','top', ...
        'XColor','k', ...
        'YColor','k', ...
        'XMinorTick','off', ...
        'YMinorTick','off');
    grid(ax, 'off');
    ax.XLabel.FontName = 'Arial';
    ax.YLabel.FontName = 'Arial';
    ax.Title.FontName  = 'Arial';
    ax.XLabel.FontSize = 8.0;
    ax.YLabel.FontSize = 8.0;
    ax.Title.FontSize  = 8.2;
    ax.XLabel.FontWeight = 'normal';
    ax.YLabel.FontWeight = 'normal';
    ax.Title.FontWeight  = 'normal';
    delete(findobj(ax, 'Tag', 'TopRightFrameLine'));
    PSI_drawTopRightFrame(ax, 0.75);
end
