function PSI_OverlayCropRectangle(ax, crop_rect, edge_color, line_width)
    rectangle(ax, 'Position', crop_rect, ...
        'EdgeColor', edge_color, ...
        'LineStyle', '--', ...
        'LineWidth', line_width);
end
