function PSI_FormatImageAxes(ax, plot_style)
    set(ax, ...
        'Color', 'w', ...
        'FontName', plot_style.font_name, ...
        'FontSize', plot_style.font_size_axis, ...
        'LineWidth', plot_style.axis_line_width, ...
        'XColor', 'k', ...
        'YColor', 'k', ...
        'Box', 'on', ...
        'Layer', 'top', ...
        'XTick', [], ...
        'YTick', []);
    axis(ax, 'image');
end
